### ISSUE TITLE
CopyInto api

### ISSUE THREAD

**Issue by gamitWeb** [fixer-m/snowflake-db-net-client#18]
Hi, Do you have a copy into api in the clienct senario is that I am trying to upload stagging csv file from azure blob to snowflake table also can I pass from column and to column in copy into query ?

**Comment by fixer-m** [comment]
Hi!
Yes, uploading files from Azure Blob should work. Run your query with `ExecuteScalarAsync()` method. 
Here is the [documentation for COPY INTO command](https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html). 
If I understood correctly, it supports column mapping, i.e. you can specify which column take from from file and to which column upload data.
