### ISSUE TITLE
RestClient HttpClient Timeout

### ISSUE THREAD

**Issue by george-int21h** [fixer-m/snowflake-db-net-client#21]
Can you set the timeout to 60 minutes just like on the ChunksDownloader? Is quite useful for long running queries. I can raise a PR but not sure if you accept any.

**Comment by mbwilding** [comment]
I have a pull request up for something unrelated to this, been there a while. Not sure if he checks them.

**Comment by george-int21h** [comment]
Can you also increase the timeout as part of the same PR? Is a trivial change.

**Comment by fixer-m** [comment]
@george-int21h Sure, thanks! I've changed timeout to 1 hour, updated package version will be released soon.

**Comment by fixer-m** [comment]
@george-int21h Done. Version 4.0.0 has increased timeout (1h) for http client.

**Comment by george-int21h** [comment]
Looks good. Thank you
