### ISSUE TITLE
The HttpRequestMessage reuse leads to the exception

### ISSUE THREAD

**Issue by yzhoholiev** [fixer-m/snowflake-db-net-client#31]
**Given**: send the query
**When**: the session is expired
**Then**: the request should be retried with the newly obtained session

**Expected result**: The request is successfully made.
**Actual result**:  The exception is thrown:
```
System.InvalidOperationException: The request message was already sent. Cannot send the same request message multiple times.
```

The issue is in the `HttpRequestMessage` instance reuse during the retry. A new instance should be created for every request.
https://github.com/fixer-m/snowflake-db-net-client/blob/3c2a17cd2060ee1955964a8f852d78738d7c0857/Snowflake.Client/SnowflakeClient.cs#L231

**Comment by fixer-m** [comment]
@yzhoholiev Hi! 
Thanks for this report! This should be fixed now in 0.4.4.
