### ISSUE TITLE
Feature request: ExecuteScalar<T> and ExecuteScalarAsync<T>

### ISSUE THREAD

**Issue by Tsanton** [fixer-m/snowflake-db-net-client#32]
Hi,

First of all; great client!
I'm wondering if you would consider altering the ExecuteScalars to accept a generic of type string, int, double, bool etc..?
Typical usages will be `select count(1)` and the like^^

Will make the code look cleaner if we could remove the type casting.

Wouldn't mind having a crack at it if you're pressed for time.

Speak soon!

/T

**Comment by fixer-m** [comment]
@Tsanton Hi! 
Thanks, that's a nice improvement. This is implemented now in 0.4.4. Commit: https://github.com/fixer-m/snowflake-db-net-client/commit/ebac54f2100a108aec9f50354e0c4f61f75351a4
