### ISSUE TITLE
OutOfMemory Exception

### ISSUE THREAD

**Issue by georgebarbu** [fixer-m/snowflake-db-net-client#33]
Hi, when using the new ChunkDownloader with default 4 threads on a large dataset I get an OutOfMemoryException in GetChunkContentAsync. The underlying JsonSerializer blows up when trying to create a List<T>
If I set it to 1 thread no issues. Same request.

**Comment by colgreen** [comment]
Do you have any more details for this?  E.g. a call stack trace? Do you know the approximate size of the data you were trying to retrieve? Thanks.

**Comment by colgreen** [comment]
Can you remember if your dataset had large binary columns in it? And if so do you an approximate size of the largest binary results? Thanks.

**Comment by georgebarbu** [comment]
Hi, the issue was the large payload, the result set was above 45M rows no binary data just varchar, timestamp and number. The OOM exception was triggered internally in the JsonSerializer more specifically when trying to new up a List<string> in the ChunkDownloader class. The problem has been made worse by the new parallel chunk downloader as is using multiple threads increasing memory pressure. If I set the chunk downloader to 1 thread then it worked fine but obviously is much slower. I've changed my implementation to pagination to avoid massive datasets.

**Comment by fixer-m** [comment]
@georgebarbu Hi,  

I'm gonna release new version with @colgreen great improvements in memory allocations - this might help.

**Comment by georgebarbu** [comment]
Sounds great, I'll leave a feedback after I test the new release

**Comment by georgebarbu** [comment]
The update looks fine
