### ISSUE TITLE
Version of REST API used

### ISSUE THREAD

**Issue by EikeKortz** [fixer-m/snowflake-db-net-client#34]
We are using your code. Unfortunately our sec team now raised a red flag as their scanners showed an unknown driver accessing snowflake. AFAIK fixer-m is using the standard SNFLK REST API?  Can you provide some more insights here and help me out?

**Comment by fixer-m** [comment]
@EikeKortz Hi! 
Did you mean SF driver name? Which can be seen in SF access logs? 
Yes, each "driver" uses its own driver name. For example this library uses ".NET_Snowflake.Client" and [official driver uses](https://github.com/snowflakedb/snowflake-connector-net/blob/9c4bd0106983c485ef0fdfe2aac5d7f247b73bb2/Snowflake.Data/Core/RestParams.cs#L61) just ".NET". 

> AFAIK fixer-m is using the standard SNFLK REST API?

Well, yes, this client uses the same Snowflake API, which is used by official connector. However for some reason this API doesn't have official documentation. There is also another public API, they call it [Snowflake SQL API](https://docs.snowflake.com/en/developer-guide/sql-api/index.html) - this is kinda new version of previous API, it's under development right now, but basic methods already works and it has documentation.
