### ISSUE TITLE
Unable to deserialize date from the format  YYYY-MM-DD hh:mm:ss[.nnnnnnn]

### ISSUE THREAD

**Issue by nadjalla** [fixer-m/snowflake-db-net-client#36]
Dates in datetime2 format (YYYY-MM-DD hh:mm:ss[.nnnnnnn]) failed to deserialize while using the mapper.
`QueryAsync<T>(sqlQuery)` fail if `T` have DateTime property that have datetime2 in snowflake database

**Comment by fixer-m** [comment]
@nadjalla Hi! Sorry for a late response. 

I don't see **DateTime2** in [Snowflake date-time types](https://docs.snowflake.com/en/sql-reference/data-types-datetime). Is it some sort of **TIMESTAMP**?

Check that you use correct C# types for mapping: 

> TIMESTAMP_TZ and TIMESTAMP_LTZ => DateTimeOffset
> TIMESTAMP_NTZ => DateTime

**Comment by nadjalla** [comment]
Thanks, I will check to make sure I'm using the right C# type
