### ISSUE TITLE
Installation failed with .NET Framework 4.6

### ISSUE THREAD

**Issue by svenover** [fixer-m/snowflake-db-net-client#8]
Hi,

I found your client and I would like to use it but the NuGet Manager process told me that it is not possible.

Error Message.

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Snowflake.Client 0.3.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			

I have a basic Winforms application with .NET Framework 4.6.

May I ask for help to install the client? What I'm doing wrong?

Many thanks in advance.
Sven

**Comment by fixer-m** [comment]
@svenover, Hi!

**Snowflake.Client** targets **.NET Standard 2.0**, which means that minimum supported version of .NET Framework is **4.6.1**. Look at this table: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Possibly you can upgrade your project target framework from 4.6 to 4.6.1 - then it will work.

**Comment by svenover** [comment]
Many many thanks. 

Sorry, with your answer, I learned more about the wording .NET Standard 2.0

Have a nice day. 
Sven

Am 23.03.2021 um 17:16 schrieb Ilya Bystrov ***@***.***>:

﻿
@svenover, Hi!

Snowflake.Client targets .NET Standard 2.0, which means that minimum supported version of .NET Framework is 4.6.1. Look at this table: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Possibly you can upgrade your project target framework from 4.6 to 4.6.1 - then it will work.

**Comment by svenover** [comment]
All is fine.
